### ISSUE TITLE
Implementation enhancements

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#155]
A list of possible nshmp-haz implementation changes and enhancements for possible consideration by the NSHMP Steering Committee, but not necessarily a high priority:

* Follow GMM author guidance on rake to fault-style conversions (#9)
* Consistent use of Somerville scaling relation in CEUS (#10)
* Consistent zHyp model (#18, #7)
* Grid source rate scaling with latitude (#8)
* Are CEUS ground motion clamps still appropriate - **clamps disabled with NGA-East**
* Deprecate and remove 'floats' attribute for MFDs (#12)
* Improve config validation #207
* See other issues tied to [2020 update](https://github.com/usgs/nshmp-model-cous-2018/issues)

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/39
