### ISSUE TITLE
Handle out of range deagg return periods and IMLs

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#169]
Note how such values are handled; some scenarios likely fail while others produce 0 values.

**Comment by pmpowers-usgs** [comment]
Note email exchanges with Franke's group re return periods out of range.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/169
