### ISSUE TITLE
Gmm period interpolation

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#17]
Develop ability to interpolate between periods; useful when building response spectra when sources use Gmm's with different period support. See #16

**Comment by ashumway-usgs** [comment]
This is going to be important when we start running the multi-period spectra maps. The 2014 NSHMP Western US model uses the Atkinson & Macias (2009) GMM for Interface sources, and we need to run it for 0.75 seconds, which is not an original supported period for that GMM. We interpolated coefficients for this period in the Fortran code.

**Comment by pmpowers-usgs** [comment]
Although this ticket remains open, the Atkinson & Macias '09 coefficients for 0.75s have been copied over from nshmp-haz-fortran in #166

**Comment by pmpowers-usgs** [comment]
Also copied over Zhao '06 0.75s coeffs in #175

**Comment by pmpowers-usgs** [comment]
Figure out how to add support for interpolated periods such that Gmm.supportedImts() returns correct superset of those supported via CoefficientContainer and those supported via interpolation. Will require GmmInterpolator (or similar) class that will perform calc() using the periods above and below.

**Comment by pmpowers-usgs** [comment]
-[ ] Add interpolation IMTs to config
-[ ] Consider trailing "i" to identify interpolated results; however, this may not apply to all GMMs
-[ ] Figure out how to handle deagg of interpolated IMT

**Comment by pmpowers-usgs** [comment]
Considering the foregoing, generalized interpolation is difficult. Moreover, most ground motion model developers are now well aware of the broad spectrum support desired by the engineering community and are developing models accordingly. It will be easier in the near term to make modifications to those few GMMs that require additional short and long period support.

**Comment by pmpowers-usgs** [comment]
See also #189 and PR #345
