### ISSUE TITLE
System Sources: allow multiple ruptures for single set of sections

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#184]
Currently the system source parser expects a 1:1 mapping of sections to ruptures in each system source folder. To better accommodate uncertainty analysis logic tree variants in the future this should be modified to permit 1:many. Any changes need to consider UCERF3 and AK2007 modeling approaches.

For example, CH and GR variants of AK2007 system sources are currently in the same file but it would be preferable that they are separate.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/40
