### ISSUE TITLE
Got error message

### ISSUE THREAD

**Issue by CGS-ruichen** [usgs/nshmp-haz#193]
Peter, 

I have been getting the following  "error". DeaggCalc completes the calculations anyway and results look reasonable. Could you please clarify whether this affects the results? 

Thanks, Rui

Error message:

DeaggCalc: error
 Arguments: [..\..\..\..\nshmp-model-cous-2014\Western_US, SanMateo_LS2.csv, 475, configPGA.json]

java.nio.file.FileSystemException: .\nshmp-haz-log-1 -> curves\DeaggCalc.log: The process cannot access the file because it is being used by another process.

**Comment by pmpowers-usgs** [comment]
Hi Rui,

Sorry... no, it does not affect results. I'm going to work on a fix in the
next few days and will let you know. It's something on Windows systems
where the log file from the calculation cannot be copied to the output
directory.

Peter

**Comment by pmpowers-usgs** [comment]
The failure of the log file to be written/moved masks a subsequent failure trying to serialize the config file.

To move the log file, close  its FileHandler; to serialize the config, register the Path interface serializer as a typeHeirarchyAdapter instead of a plain TypeAdapter.
