### ISSUE TITLE
Add Graizer 2017 CEUS GMM, which is an alternative to the Graizer 2016 GMM

### ISSUE THREAD

**Issue by ashumway-usgs** [usgs/nshmp-haz#222]
Graizer updated his NGA-East Seed model (NGA_EAST_SEED_Graizer) with his Graizer 2016 model. The 2017 model is an alternative to the 2016 model. He recommends using the 2016 and 2017 models instead of his NGA-East Seed model. He has provided tables of median ground motions for the 2017 model, similar to the NGA-East format.

**Comment by pmpowers-usgs** [comment]
@ashumway-usgs supplied NGA-East compatible ground motion tables.
