### ISSUE TITLE
Add Shahjouei and Pezeshk 2016 CEUS GMM, which is an update to the NGA_EAST_SEED_SP15 model

### ISSUE THREAD

**Issue by ashumway-usgs** [usgs/nshmp-haz#223]
Shahjouei and Pezeshk have updated their NGA-East Seed Model (SP15) with a new model. Their BSSA paper provides a functional form and coefficient tables for median ground motions and sigma.

**Comment by pmpowers-usgs** [comment]
We were not provided with seed model tables (like Graizer did). Rather, the update is a full fledged model with functional form, coefficients for all periods we require, and both mean and standard deviation models of ground motion. Currently the model is listed/identified in `Gmm.java` among the NGA-East seed models, however it really could be considered standalone.
