### ISSUE TITLE
New GMM verification and followup 

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#228]
Following preliminary implementations of new GMMs, this issue summarizes open questions and remaining work to be done.

__Zhao et al. 2016 (#225):__
- [ ] Unit tests.
- [ ] Review site amplification model; smoothing between vs30; should hard rock be added as an anchor/key above "Site Class I"?
- [ ] 0.75 s not supported; needs interpolation; 7.5s, 10s?
- [ ] Check nonlinCrossover() notes; there are edge cases where Zhao recommends using approximate functional forms from Zhao, Hu  et al. (2015), but these are difficult to follow 

__Graizer & Kalkan 2016 (#224):__
- [ ] Unit tests
- [ ] Review basin term; default at 150m for CA (pers. comm.); interpolating between z1p0 and z2p5; Grazier supplied z2p5 to z1p5 conversion 11/7/17

__Atkinson 2010 (#226):__
- [ ] Unit tests
- [ ] Review depth dependence once updated HI source models implemented

__Wong et al. 2015 (#227):__
- [ ] Unit tests
- [ ] Needs steam model (so does McVerry for use of volcanic model in HI)

__Sub models with CB14 basin (#256):__
- [ ] Unit tests
- [ ] BcHydro12
- [ ] A&M09
- [ ] Zhao06 (+ site term smoothing)

__NGA-East site amplification (#257):__
- [x] Unit tests #406

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/41
