### ISSUE TITLE
Consider Increasing Upper Range Limit of Z2.5

### ISSUE THREAD

**Issue by ashumway-usgs** [usgs/nshmp-haz#229]
In the Site.java file (line #85), the upper range limit for z2.5 is set to 5.0. I have seen some data sets that have Z2.5 values of 7+ km. I'm not sure what a realistic upper limit would be, but 5.0 seems to be too low.

**Comment by mmoschetti-usgs** [comment]
Why don't we leave this unconstrained for now? We are testing basin amplifications from the various GMMs. If we find any funny behavior, we can be in touch with the developers and limit the Z-parameter values to an appropriate range.

**Comment by pmpowers-usgs** [comment]
It's always good to have bounds that let you know when something is totally unreasonable (e.g. a negative value in this case). We'll increase the upper limit, and it can be further increased if necessary.

**Comment by pmpowers-usgs** [comment]
Resolved in #232
