### ISSUE TITLE
Add basin effects to non-NGAW2 GMMs

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#256]
In order to consider basin effects everywhere throughout the WUS, subduction interface and slab GMMs need to have an amplification term added. Art Frankel recommended we use the Campbell and Bozorgnia 2014 (NGAW2, z2p5) model. This needs to be added to BcHydro, Atkinson & Macias, and Zhao06. In order to not disrupt the existing models, this additions should be handled via subclasses that will have their own identifiers (e.g. ZHAO_06_INTER_BASIN).

- [x] Expose CB14 basin term
- [x] A&M09 subclass
- [x] BcHydro12 subclasses
- [x] Zhao06 refine site-vs30 interpolation
- [x] Expose Zhao16 site class
- [x] Refactor exiting SiteClass to GmmUtils.CeusSiteClass
- [x] Clean Zhao06 coeffs to match pub; precision

**Comment by pmpowers-usgs** [comment]
The addition of the CB14 basin amplification model necessitated the deprecation of several periods variously available in the original subduction GMMs: [0.6, 0.7, 0.8, 0.9, 1.25, 2.5, 6.0]

**Comment by ashumway-usgs** [comment]
After further discussion about modification to the subduction GMMs to include the CB14 basin term we have decided that we need to remove the Vs30 term (and any implied basin terms) from the subduction GMMs and then add the CB14 Vs30 and basin terms to the GMMs. Simply adding the CB14 basin term without removing the original Vs30 term is incorrect?

**Comment by pmpowers-usgs** [comment]
Follow up with @emthompson-usgs regarding reference site term.

**Comment by pmpowers-usgs** [comment]
The consideration of basin effects has been re-implemented in the subduction GMMs using period-specific ground motion for a rock-reference site added (in log space) to the site/basin term computed using CB14, with reference to the Vs30 value considered 'rock' by the subduction GMM (AM_09=760, BCHYDRO_12=1000).

**Comment by pmpowers-usgs** [comment]
- [ ] Needs to be implemented as amplification only
- [ ] Check that site provider is working as expected usgs/nshm-cous-2018#14

**Comment by pmpowers-usgs** [comment]
Subduction models now use `CambellBozorgnia.BasinAmp` and should exhibit amplification only effects; see #319

**Comment by pmpowers-usgs** [comment]
Resolved in #319
