### ISSUE TITLE
Add capability to reference agrid file in source file

### ISSUE THREAD

**Issue by ashumway-usgs** [usgs/nshmp-haz#261]
For the one-year induced seismicity models, there are a large number of agrids. Some sources use the same agrids. It might be beneficial to allow a source file to reference information from an agrid (e.g. line in source file that points to the name of an agrid file), rather than needing to duplicate this data in multiple source files.

**Comment by pmpowers-usgs** [comment]
@mmoschetti-usgs @cmueller-usgs 

The file format we will use for this will be CSV. The format will have a header row that will identify:
```
lon, lat [m, rate, a, b, mMin, mMax, dMag, cMag] 
```

At a minimum `lat` and `lon` must be present. The presence of other values/columns will be a function of the MFDs being used for a particular source. All additional columns are optional. Headers and columns can be in any order.

**Comment by pmpowers-usgs** [comment]
As an intermediate step, we will also support the `<node />` elements being in a separate file that would be identified with the suffix `*.nodes` as it would not be well-formed XML.

**Comment by pmpowers-usgs** [comment]
Support for per node focal mech maps was added for UCERF3; if we want to support this along with external file support, columns/headers should be added for `STRIKE_SLIP`, `NORMAL`, and `REVERSE` ([FocalMech enum](https://github.com/usgs/nshmp-haz/blob/master/src/gov/usgs/earthquake/nshmp/eq/fault/FocalMech.java)) and if one is included, the other two also must be.
