### ISSUE TITLE
Create EQ probability maps

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#290]
Create earthquake probability maps using the 2014 COUS model. 

The RateCalc program can be used to create a CSV file of `lon,lat,M1,M2,M3,...` using a the following rate calc configuration:

```json
  "rate": {
    "bins": {
      "mMin": 5.0,
      "mMax": 8.5,
      "Δm": 0.5
    },
    "distance": 50.0,
    "distributionFormat": "CUMULATIVE",
    "valueFormat": "POISSON_PROBABILITY",
    "timespan": 1
  }
```

* Datasets should be generated for the following timespans: `[1, 5, 10, 20, 30, 50]` years
* The csv file headers will list magnitude bin centers (e.g. 5.25), but the probabilities listed are for all magnitudes greater than the lower bin edge (e.g. M≥5.0).
* Data should be handed off to GIS group. ScienceBase?

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/290
