### ISSUE TITLE
Interpolator clean up

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#298]
* Addt'l documentation
* Builder.decreasingX is not clear; we're really talking about y-values monotonically increasing or decreasing: "Because we assume (enforce?) x-values are increasing and non-repeating, deriving y-from-x is straightforward. However, when deriving x-from-y the interpolator searches ascending though any supplied x-y data and needs to know if y-values increase or decrease after the fist value."
* Consider public validating methods and private non-validating; may not be possible to access in package without explicit 'nonValidating' method signatures.
* Consider extrapolation flag (only permitted for y-from-x)
* Consider returning NaN instead of 0 for out of range y-from-x targets; if x-values are in log space, then the interpolator is actually returning a value of 1 (this is currently producing misleading desegregation results for out of range return periods)
* Write tests

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/44
