### ISSUE TITLE
OFR

### ISSUE THREAD

**Issue by haller-usgs** [usgs/nshmp-haz#32]
Figure 65 (p. 103)  is incorrect. New Adobe Illustrator version on PCMAC/NSHMP/FINAL_IP-052282Documentation/FinalFIGS. Low res image attached
![fig65v2](https://cloud.githubusercontent.com/assets/7432678/10054699/ac9d8872-61ef-11e5-9794-c83b37793bb5.png)

**Comment by pmpowers-usgs** [comment]
moved to nshmp-haz-fortran [#23](/usgs/nshmp-haz-fortran/issues/23)
