### ISSUE TITLE
Review Math.rint() usage 

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#322]
`rint` uses `RoundingMode.HALF_EVEN`. The method is really intended for unbiased statistical analysis and will produce inconsistent results when used in other ways; for example, when trying to compute an  incremental MFD bin center that is less than some magnitude.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/45
