### ISSUE TITLE
Deaggregation improvements and updates

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#389]
Grab bag of updates and improvements; some will be addressed with source model restructuring and hazard model/calc updates; others on the service side.

* Update slab names to reflect depth slice.
* Consider combining grid sources into one summary; drop lat-lon-az averages
* Wasatch consolidation (cluster and fault branches)
* Consolidate grid/rlme branch reporting, e.g. Charleston

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/46
