### ISSUE TITLE
fltrate transition

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#390]
Prior USGS codes relied on [fltrate.v2.f](https://github.com/usgs/nshmp-haz-fortran/blob/master/src/util/fltrate.v2.f) to convert slip/displacement rates and fault geometries to CH mMax, a-values, GR mMin and mMax values and bin widths, and finally output the input files with MFD's etc that hazflt/grd etc would use.

In refactoring nshmp-haz models to JSON and including uncertainty, the functions of fltrate will be implemented at load time. Models will not be defined by prescriptive MFDs but their slip rate ad other original data instead, coupled with logic tree structure.

Notes:
* Remember to impose WUS mMax caps SS=8.0 R/N=7.5, regardless of mag scaling M

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/47
