### ISSUE TITLE
Change ExceedanceModel enum to ProbabilityModel

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#47]
Although hazard is generally presented in terms of probability of exceedance, for deaggregation we want the option of computing probability of occurrence. The enum should therefore be renamed with instances providing both `probability()` and `exceedance()` methods.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/32
