### ISSUE TITLE
Consider changing how results are handled from command-line calls.

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#66]
Current results are sent to files in a `results` folder. Subsequent results override previous runs. Subsequent runs also do not remove results from previous runs. This can lead to polluted results directories.

Perhaps results should go into a `results/TIMESTAMP` directory to stay unique.

**Comment by pmpowers-usgs** [comment]
The original output design assumed users would copy a custom config to a directory which would then be used for output of results. In practice this is proving odd to use. An alternative approach that has been suggested is to allow the config to specify an output directory; the default would be the cwd(.)

**Comment by pmpowers-usgs** [comment]
The default output directory is now called "curves". A user can override this with a specific directory/path. Results will never overwrite existing results in favor of incrementing the output directory name.
