### ISSUE TITLE
Consider changing the argument order for HazardCalc command line usage

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#67]
Consider changing the argument order for `HazardCalc` command line usage so custom sites are specified before custom configuration. It seems more likely to have a custom set of sites of interest rather than custom configuration for the default site.

**Comment by pmpowers-usgs** [comment]
Move all site and map specification out of config. Sites will always will always be processed by supplying a file (geojson or csv) as first argument, followed by custom calc configuration. Also should consider single site, see #93.

**Comment by pmpowers-usgs** [comment]
All site spec has been removed from config. User must specify site(s), see new [Sites](https://github.com/usgs/nshmp-haz/wiki/Sites) wiki entry. This may be followed by an optional overriding calc config.
