### ISSUE TITLE
Add a benchmark test suite

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#71]
Test full application end-to-end for known input and output. Consider 34 fixed cities or similar list. Define clear criteria for passing (results should be within some delta).

Create benchmark statistics for this to measure performance.
- Speed
- Memory footprint
- etc...

**Comment by pmpowers-usgs** [comment]
End-to-end tests added in #378. Memory and speed are largely platform dependent and will have decreased value as future development considers more distributed computational pathways.
