### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#74]
A continuous integration solution should be leveraged by this repository. Continuous integration is a means of automatically checking each commit/pull request against a suite of unit-, integration-, and/or other- tests; it can optionally be used for shipping/deployment as well.

Integration hooks should be configured on the repository such that continuous integration is run prior to any pull request being merged. The latest continuous integration results should be immediately visible on the repository README file.

Results of unit tests and/or coverage reports can also be automatically included on the gh-pages branch (or other location) to clearly show the current state of the project.

**Comment by pmpowers-usgs** [comment]
update build.xml test target for travis

**Comment by pmpowers-usgs** [comment]
Travis CI added/enabled some time ago.
