### ISSUE TITLE
Reorganize packaging

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#76]
Source code lifted directly from the OpenSHA project should continue to live in the org.opensha… (or similar) package; however source code developed specifically for the nshmp-haz project should be moved to a gov.usgs.nshmp... (or similar) package.

**Comment by pmpowers-usgs** [comment]
Also consider moving 'programs' up a level. Consider interface for common program elements moving forward.

**Comment by pmpowers-usgs** [comment]
Most truly USGS specific code has been separated out to the web-services repository. There will be a future discussion as to how to reintegrate nshmp-haz with OpenSHA at which point some newer packages (calc?) may be designated as gov.usgs.earthquake. Until then, the program package has been removed in favor of moving programs up one level.
