### ISSUE TITLE
Move documentation to gh-pages

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#77]
The documentation is out of date. Many references to refactored classes still exist and it leads one to question what else may not be accurate. Consider moving the documentation from a Wiki to the gh-pages branch. This has many benefits including:
- gh-pages can be managed at the same time as the source code itself.
- gh-pages can go through the same pull request process for review prior to integration.
- gh-pages uses simple Markdown and can benefit from Jekyll templating to produce a more USGS visually-compliant product.
- gh-pages can be updated as part of an integration hook to keep it up-to-date with the code itself.

**Comment by pmpowers-usgs** [comment]
This will take a certain amount of effort. Currently the documentation in the project wiki is independently versioned and the convenience of the existing markdown-based wiki weighs against moving a lot of things around and adopting new documentation practices at this time. The api documentation (JavaDoc), which is automatically generated but manually pushed, currently resides on gh-pages.

This issue as part of this milestone will be closed but referenced by a new issue to keep it on the books (#152)
