### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#78]
Consider a new overall documentation structure.
- Home
- Getting Started
  - Obtaining Source Code
    - Following the first release of the software, add links to download a zip/tarball of the released software package.
  - Building
    - Building should not make assumptions but rather explain each step required to successfully build the software.
    - Include variations, as appropriate, for each supported OS.
    - Document each available built target in build.xml.
- Source Models
  - Obtaining USGS models for use
  - Source types
  - GMM
  - Config
- Applications
  - HazardCalc
    - Usage
    - Output
    - Example commands to run code
  - Deaggregation
    - Usage
    - Output
    - Example commands to run code
  - Response Spectra
    - Usage
    - Output
    - Example commands to run code
- Dependencies
- Functional PSHA
- API Docs

**Comment by pmpowers-usgs** [comment]
Some of this restructuring has been applied in the wiki. Other changes may be considered as more applications (e.g. response spectra) become officially supported.
