### ISSUE TITLE
Add a Linter to the project

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#79]
A Linter should be implemented for this project. Linting validates the source code against the style guide to ensure source code remains compliant. A CONTRIBUTING.md file should be added to the repository root directory in order to clarify the style guide expectations for contributions (among other things).

A task should be added to the build.xml file to execute the linter against existing source code.

**Comment by pmpowers-usgs** [comment]
Closing as part of milestone. See #153
