### ISSUE TITLE
Clean and condense GriddedSurface hierarchy

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#85]
There are a lot of poorly named and unused methods that were added to support CompoundSurfaces in OpenSHA but that are not needed here.

Also consider guava's ArrayTable as a replacement for Container2D.

**Comment by pmpowers-usgs** [comment]
Starting with LocationList cleanup and reorganization

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/34
