### ISSUE TITLE
Adhere to author defined focal mech cutoffs

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#9]
Current GMM implementations (adhering to past practice in the fortran codes) do not adhere to author defined focal mechanism cutoffs. This was due to the fact that the fortran input files could only handle integer based identifiers for fault-type (1,2, or 3) instead of using rake directly.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/31
