### ISSUE TITLE
Improve surface.getPerimeter() implementations

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#91]
getPerimeter() implementations that do exist are lazy and called every single time a site is on a hanging wall. What's worse, Distance calls getPerimeter TWICE for hanging-wall sites so there may be some performance gain. Rupture borders/areas should be cached after lazy creation.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/36
