### ISSUE TITLE
Update grid source MFD handling

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#97]
Grid source implementation is currently incomplete as it applies to the 2014 NSHM. Multiple default MFD's of the same type are not processed. Initial implementations, based on the 2008 NSHM, assumed that grids would always be of type GR or SINGLE and each node would map to a single default. This design was also driven by the edge case of CA_map, where sources/MFDs in California had their rates reduced by 1/3 for M≥6.5 so a source could be GR or INCR but not both.

There are now a significant number of grid sources that have logic trees of SINGLE MFDs, defined as defaults (e.g. Charleston RLME). We want to be able to process these individually or combine them for efficiency. Also, the large western us grids have 'gr', 'ch', and 'm8' variants, which have historically been separated, but all of which have the same a-values (which are therefore repeated across 3 large files).

A better implementation would have the branches of the MFD logic tree defined as DefaultMFDs, which would be applied to every source. 'a' values and/or 'rates' would be supplied on a per-source basis. Any mMax overrides would be supplied in <IncrementalMfd id="id" mMax="7.5"/> tags attached to a source.

**Comment by pmpowers-usgs** [comment]
Example:
```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!-- Possible enhancements to grid format -->
<!-- Existing format is 1:1 conversion of fortran inputs, but completely
     separates logic tree branches into separate files -->
<!-- a-values are the same across gr, ch, and m8 branches of each smoothing model -->
<!-- MFD id identifies logic tree branch -->
<!-- Can combine any MFDs as long as mMin and dMag match; scan for max mMax -->
<!-- Use all defaults for each source-->
<!-- Override by matching branch id -->
<!-- Default MFD branch ids must be unique -->
<!-- Default MFDs can be of any type -->

<GridSourceSet id="-1" name="EXTmap_2014_adaptive" weight="0.4">
  <Settings>
    <DefaultMfds>
      <IncrementalMfd a="0.0" b="0.8" dMag="0.1" id="GR" mMax="7.45" mMin="5.05" weight="0.3" type="GR" />
      <IncrementalMfd a="0.0" b="0.8" dMag="0.1" id="CH" mMax="7.45" mMin="5.05" weight="0.6" type="GR" />
      <IncrementalMfd a="0.0" b="0.8" dMag="0.1" id="M8" mMax="7.95" mMin="5.05" weight="0.1" type="GR_TAPER" cMag="7.5" />
    </DefaultMfds>
    <SourceProperties 
    	focalMechMap="[STRIKE_SLIP:0.333,NORMAL:0.667,REVERSE:0.0]"
    	magDepthMap="[6.5::[5.0:1.0]; 10.0::[1.0:1.0]]"
    	maxDepth="14.0"
    	ruptureScaling="NSHM_POINT_WC94_LENGTH"
    	strike="NaN"/>
  </Settings>

  <Source a="1.0363006e-11">-126.5,24.6,0.0</Source>
  <Source a="0.11664908" location="-104.6,30.5,0.0">
  	<IncrementalMfd id="GR" mMax="6.45" />
  	<IncrementalMfd id="CH" mMax="7.1" />
  </Source>
  <Source a="0.11146883" location="-104.6,30.5,0.0">
  	<IncrementalMfd id="GR" mMax="6.45" />
  	<IncrementalMfd id="CH" mMax="7.38" />
  </Source>
</GridSourceSet>
```

**Comment by pmpowers-usgs** [comment]
This has been addressed to ensure that all MFD's are being considered, but logic tree branches are not yet properly handled. Removing 'bug' tag for now.

The structure above will work, but requires additional modification to gridParser and gridSourceSet. One path forward involves initializing both collapsed mfd sourceSets and branch-preserving sourceSets. These would be stored in standard and optimized multimaps of source sets in a HazardModel and which to use would depend on calcConfig.performance.collapseMfds. This would not restrict a significant performance option from being keyed to the initialization process.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-lib/issues/37
